version: '3.8'

services:
  # Service for our off-chain keeper bot
  keeper:
    build:
      context: .
      dockerfile: offchain/Dockerfile
    environment:
      - RPC_URL=http://host.docker.internal:8545
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # Ensures the keeper restarts if it fails
    restart: unless-stopped