global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: 'keeper-bot'
    static_configs:
      - targets: ['keeper:9091'] # 'keeper' is the service name in docker-compose, 9091 is the port we expose.
